INSERT INTO artesanias (nombre, descripcion, imagen) VALUES
('Ruana de Nobsa', 'Tradicional ruana tejida a mano con lana virgen, característica de Nobsa, ideal para el clima frío de la región.', ''),
('Sombrero Aguadeño', 'Sombrero elaborado con fibras naturales, característico de Aguadas, Boyacá, famoso por su durabilidad y elegancia.', ''),
('Mochila de Fique', 'Mochilas tejidas con fibra de fique, coloridas y representativas de la cultura campesina boyacense.', ''),
('Tejidos de Iza', 'Tejidos de lana elaborados en Iza, famosos por su calidad y por mantener vivas las tradiciones.', ''),
('Alfarería de Ráquira', 'Piezas de cerámica hechas a mano en Ráquira, Boyacá, conocidas por sus diseños coloridos y tradicionales.', ''),
('Candelabro de Ráquira', 'Candelabros de cerámica, parte de la alfarería tradicional de Ráquira, con detalles artesanales únicos.', ''),
('Chal de Paipa', 'Chal tejido a mano con lana en Paipa, famoso por su suavidad y calidez.', ''),
('Collar de Tagua', 'Accesorios elaborados con semillas de tagua, un material natural conocido como el marfil vegetal.', ''),
('Poncho Boyacense', 'Ponchos tejidos a mano, una prenda tradicional de la región que representa la identidad cultural de Boyacá.', ''),
('Sombrero de Fique', 'Sombrero tejido con fique, representativo del trabajo artesanal de los campesinos boyacenses.', ''),
('Cerámica Decorativa de Ráquira', 'Piezas decorativas hechas de cerámica en Ráquira, con detalles únicos que representan la cultura de la región.', ''),
('Bolso de Fique', 'Bolsos tejidos con fibras de fique, coloridos y utilizados comúnmente en el campo.', ''),
('Macetas de Ráquira', 'Macetas artesanales de cerámica, ideales para jardines y decoraciones interiores.', ''),
('Vasija de Cerámica de Ráquira', 'Vasijas hechas a mano, usadas para almacenar alimentos y bebidas en la tradición boyacense.', ''),
('Bufanda de Nobsa', 'Bufanda tejida con lana virgen en Nobsa, famosa por su calidez y diseño.', ''),
('Sombrero de Paja de Tenza', 'Sombrero hecho con paja en Tenza, conocido por su resistencia y estilo.', ''),
('Aretes de Tagua', 'Accesorios hechos con semillas de tagua, un símbolo del uso sostenible de recursos naturales.', ''),
('Ruana de Cuitiva', 'Ruanas elaboradas a mano en Cuitiva, conocidas por su diseño y calidad.', ''),
('Canasto de Fique', 'Canastos tejidos a mano con fique, utilizados en la agricultura y como elemento decorativo.', ''),
('Porta Vasos de Ráquira', 'Pequeños porta vasos de cerámica elaborados en Ráquira, con detalles coloridos y únicos.', ''),
('Ruana de Duitama', 'Ruanas tejidas a mano en Duitama, un símbolo de la tradición y la artesanía de Boyacá.', ''),
('Jarrón de Cerámica de Ráquira', 'Jarrones de cerámica decorados a mano, utilizados para adornar hogares boyacenses.', ''),
('Sombrero Boyacense', 'Sombrero tradicional hecho a mano, utilizado en las festividades y eventos tradicionales.', ''),
('Mochila de Cabuya', 'Mochilas tejidas con cabuya, muy populares entre los campesinos boyacenses.', ''),
('Camino de Mesa de Nobsa', 'Tejidos artesanales de Nobsa utilizados como decoración en mesas.', ''),
('Artesanías en Madera de Tibasosa', 'Figuras y objetos tallados a mano en madera, típicos de Tibasosa.', ''),
('Tapete de Fique', 'Tapetes tejidos a mano con fibra de fique, usados como decoración en hogares.', ''),
('Plato Decorativo de Ráquira', 'Platos de cerámica pintados a mano, representativos de la tradición alfarera de Ráquira.', ''),
('Cinturón de Cuero Artesanal', 'Cinturones hechos a mano con cuero de alta calidad, producidos en Boyacá.', ''),
('Cofre de Madera Tallada', 'Pequeños cofres tallados a mano en madera, utilizados para almacenar objetos personales.', ''),
('Figuras de Cerámica de Ráquira', 'Figuras decorativas de cerámica que representan la vida cotidiana en Boyacá.', ''),
('Sombrero Aguadeño de Fique', 'Versión del sombrero aguadeño tejido con fique, una fibra tradicional en Boyacá.', ''),
('Bufanda de Lana de Iza', 'Bufandas hechas con lana virgen de oveja, tejidas en Iza.', ''),
('Vasija Decorativa de Cerámica', 'Vasijas decoradas a mano con patrones tradicionales boyacenses.', ''),
('Bolsa de Mano de Fique', 'Bolsa tejida con fique, ideal para el uso diario y como souvenir típico de Boyacá.', ''),
('Tapete Tejido de Nobsa', 'Tapetes de lana tejidos a mano en Nobsa, un ejemplo de la artesanía local.', ''),
('Figura Religiosa de Ráquira', 'Estatuillas religiosas de cerámica, comunes en la producción artesanal de Ráquira.', ''),
('Bufanda de Paipa', 'Bufandas tejidas a mano en Paipa, reconocidas por su calidad y estilo.', ''),
('Collar de Madera Tallada', 'Accesorios hechos a mano con piezas de madera tallada, representando la naturaleza de Boyacá.', ''),
('Mantel Tejido de Nobsa', 'Manteles de lana tejida, usados en eventos especiales y decoraciones.', ''),
('Jarrón Decorativo de Ráquira', 'Jarrones de cerámica pintados a mano, utilizados en la decoración de hogares boyacenses.', ''),
('Sombrero Artesanal de Tenza', 'Sombrero de paja tejido a mano, típico de Tenza, Boyacá.', ''),
('Monedero de Fique', 'Pequeños monederos tejidos a mano con fique, utilizados como souvenir en Boyacá.', ''),
('Portarretratos de Madera Tallada', 'Portarretratos hechos a mano en madera, con detalles tallados.', ''),
('Cerámica Utilitaria de Ráquira', 'Cerámica hecha para el uso diario, como platos y tazas, elaborados en Ráquira.', ''),
('Bufanda de Nobsa', 'Bufanda de lana virgen tejida a mano, famosa por su suavidad y calidad.', ''),
('Sombrero de Lana de Paipa', 'Sombrero tejido a mano con lana de oveja, típico de la región de Paipa.', ''),
('Alpargatas de Fique', 'Zapatos tejidos con fibras de fique, comunes en la zona rural de Boyacá.', ''),
('Cartera de Cuero Artesanal', 'Carteras de cuero hechas a mano, con diseños inspirados en la naturaleza boyacense.', ''),
('Figuras Decorativas de Ráquira', 'Figuras hechas a mano en cerámica, que representan personajes y escenas típicas de la región.', ''),
('Chaleco de Lana de Nobsa', 'Chalecos tejidos con lana virgen, populares entre los campesinos y habitantes de zonas frías.', ''),
('Ruana de Fique', 'Ruanas tejidas con fique, representativas de la tradición artesanal de Boyacá.', ''),
('Platos Decorativos de Cerámica', 'Platos hechos y pintados a mano, utilizados para decorar hogares en Boyacá.', ''),
('Cojín de Lana de Nobsa', 'Cojines tejidos con lana, famosos por su suavidad y calidez.', ''),
('Collar de Madera de Tibasosa', 'Collares elaborados con piezas de madera tallada, típicos de Tibasosa.', ''),
('Cestas de Fique', 'Cestas tejidas con fique, utilizadas para almacenamiento y decoración.', ''),
('Estatuilla de Cerámica de Ráquira', 'Estatuillas decorativas de cerámica hechas a mano en Ráquira.', ''),
('Cartera de Fique', 'Carteras tejidas a mano con fique, un accesorio tradicional de la región.', ''),
('Sombrero de Cabuya', 'Sombrero tejido a mano con cabuya, utilizado en zonas rurales de Boyacá.', ''),
('Bufanda de Lana de Iza', 'Bufandas elaboradas con lana de oveja, tejidas a mano en Iza.', ''),
('Porta Incienso de Cerámica', 'Piezas de cerámica para quemar incienso, hechas a mano en Ráquira.', ''),
('Tejidos de Fique de Nobsa', 'Tejidos de fique utilizados en manteles y otros productos decorativos.', ''),
('Vasija de Ráquira', 'Vasijas de cerámica hechas a mano, típicas de Ráquira, Boyacá.', ''),
('Canasta de Fique', 'Canastas tejidas con fibra de fique, utilizadas para llevar productos agrícolas.', ''),
('Ruana de Sogamoso', 'Ruanas elaboradas en Sogamoso, hechas a mano con lana de alta calidad.', ''),
('Sombrero de Paja Toquilla', 'Sombrero tejido con paja toquilla, representativo del trabajo artesanal de Boyacá.', ''),
('Collar de Piedras Semipreciosas', 'Accesorios hechos con piedras semipreciosas de la región, típicos de Boyacá.', ''),
('Cinturón de Cuero de Paipa', 'Cinturones de cuero elaborados artesanalmente en Paipa.', ''),
('Juguetes de Madera de Tibasosa', 'Juguetes tradicionales tallados en madera, típicos de la región de Tibasosa.', ''),
('Bolso de Cabuya', 'Bolsos hechos a mano con cabuya, un producto tradicional de Boyacá.', ''),
('Copa de Cerámica de Ráquira', 'Copas de cerámica hechas a mano, usadas para ceremonias y decoraciones.', ''),
('Ruana Artesanal de Iza', 'Ruanas tejidas a mano en Iza, conocidas por sus diseños tradicionales.', ''),
('Tapete de Fique de Nobsa', 'Tapetes artesanales tejidos con fibra de fique, utilizados como decoración.', ''),
('Jarrón de Madera Tallada', 'Jarrones tallados a mano en madera, utilizados como decoración en Boyacá.', ''),
('Poncho de Lana de Sogamoso', 'Ponchos tejidos a mano en Sogamoso, utilizados en climas fríos.', ''),
('Collar de Tagua y Madera', 'Collares hechos con una combinación de tagua y madera, típicos de Boyacá.', ''),
('Sombrero de Fique de Paipa', 'Sombrero tejido a mano con fique, típico de la región de Paipa.', ''),
('Bufanda Artesanal de Iza', 'Bufandas tejidas a mano en Iza, conocidas por su calidad y estilo.', ''),
('Porta Llaves de Madera Tallada', 'Accesorio de madera tallado a mano, utilizado para colgar llaves y objetos pequeños.', ''),
('Plato de Cerámica de Ráquira', 'Platos de cerámica hechos a mano, decorados con motivos tradicionales.', ''),
('Sombrero de Paja de Nobsa', 'Sombrero tejido con paja, utilizado en eventos tradicionales de Nobsa.', ''),
('Cartera de Cuero de Paipa', 'Carteras de cuero hechas a mano, con detalles únicos y artesanales.', ''),
('Cesta de Cabuya de Nobsa', 'Cestas tejidas a mano con cabuya, típicas de la región de Nobsa.', ''),
('Ruana de Lana de Iza', 'Ruanas elaboradas con lana de oveja, tejidas a mano en Iza.', '') 
